php:
  image: product/php
  container_name: php
  hostname: php
  expose:
    - "80"
  ports:
    - "80:80"
  environment:
    - product_repo=https://github.com/Praqma/web-deployment-poc--code.git
    - LOCATION=PRODUCTION
  volumes_from:
    - datacontainer
  links:
    - db:db
db:
  image: product/mysql
  container_name: mysql
  hostname: mysql
  volumes_from:
    - datacontainer
  expose:
    - "3306"
  environment:
    - MYSQL_ROOT_PASSWORD=password
